<?php

$modversion['name'] = _MI_FETEDUJOUR_NAME;
$modversion['version'] = 1.1;
$modversion['description'] = _MI_FETEDUJOUR_DESC;
$modversion['credits'] = '';
$modversion['author'] = '<a href="http://www.sample4.net/~nicofr38/">NicoFr38</a>';
$modversion['help'] = '';
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'fetedujour.jpg';
$modversion['dirname'] = 'fetedujour';
// Sql file (must contain sql generated by phpMyAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'fetes';
// Menu
$modversion['hasMain'] = 0;
// Admin
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
// Blocks
$modversion['blocks'][1]['file'] = 'fetedujour.php';
$modversion['blocks'][1]['name'] = _MI_FETEDUJOUR_BNAME;
$modversion['blocks'][1]['description'] = 'Affiche la fete du joure!';
$modversion['blocks'][1]['show_func'] = 'b_fetedujour_show';
